### ISSUE TITLE
'Index sources and publish symbols' fails with "The given path's format is not supported"

### ISSUE THREAD

**Issue by henning-krause** [Microsoft/vso-agent-tasks#1009]
I'm using the 'Index sources and publish symbols' activity and my build fails while publishing the symbols. 

Publishing PDBs using the legacy build system is successful, so I assume my symbol server is set up correctly.

This is the relevant part of the log file:
12:42:58.072656 BaseLogger.LogConsoleMessage(scope.JobId = 2259e554-44da-414d-8cef-a69eb8c7b4f9, message = Invoke-PublishSymbols -PdbFiles [...] -Version '1744' -MaximumSemaphoreAge '1440' -Share 'https://code.myserver.de/symbols' -ArtifactName 'Symbols_$(BuildConfiguration)' -Product '10 Main' -SemaphoreMessage 'Machine: BUILD, BuildUri: vstfs:///Build/Build/1744, BuildNumber: 1744, RepositoryName: MyRepository, RepositoryUri: http://code.myserver.de/tfs/DefaultCollection/, Team Project: MyTeamProject, CollectionUri: http://code.myserver.de/tfs/DefaultCollection/ at 12/23/2015 12:42:58 UTC' -MaximumWaitTime '7200000')
12:42:58.119535 Process logging event with task handler.
12:42:58.119535 BaseLogger.LogConsoleMessage(scope.JobId = 2259e554-44da-414d-8cef-a69eb8c7b4f9, message = ##[error]The given path's format is not supported.)

The task fails with "The given path's format is not supported". 

Any clues what's going on here or how I could debug this issue?

**Comment by ericsciple** [comment]
If you set the variable (variables tab of the definition) system.debug to true you should get a stack trace in the log.

**Comment by ericsciple** [comment]
The more I am thinking about it, I think the task only supports file shares at this time. I'll ask around a bit and confirm and try and figure out if there is an easy workaround at this time.

**Comment by ericsciple** [comment]
I was able to confirm it is intentional that it only supports file shares at this time. If you need a workaround you might be able to perform symstore.exe step yourself. If you leave the "Path to publish symbols" input blank then the task will perform PDB indexing but will skip the publishing step. I'm guessing you would need to create a response file and feed it into symstore.exe. Here's a feature branch I'm working in where the publishing logic has been ported to script: https://github.com/Microsoft/vso-agent-tasks/blob/users/ersciple/m94psexetask/Tasks/PublishSymbols/PublishHelpers/PublishHelpers.psm1

**Comment by henning-krause** [comment]
Thanks for the update. I simply created a file share for now and publish the symbols to that location. It works.
