### ISSUE TITLE
Create zip file of build output

### ISSUE THREAD

**Issue by eloekset** [Microsoft/vso-agent-tasks#1079]
Do we have some tool to create a zip archive? I tried using the PowerShell command Compress-Archive from a Command Line step, but that cmdlet doesn't exist on the build server.
![2016-01-15_1617](https://cloud.githubusercontent.com/assets/791721/12356543/9328d62c-bba3-11e5-8640-09528ea08755.png)

**Comment by eloekset** [comment]
I found a way to compress a folder to a zip file using a Command Line task that uses powershell.exe with the following arguments:
-nologo -noprofile -command "& { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::CreateFromDirectory('\WebPublish\Analytics\', 'Upload.zip'); }"

It would be better to have a more convenient way to compress files and folders into zip files. Is there an easier way that I'm not aware of, or should we create a Zip task to be part of the utilities tasks?

**Comment by ericsciple** [comment]
Keep in mind only works because you happen to have the appriopriate version of .net framework installed. I think the ZipFile class is only in 4.5.2, and I think the agent only requires 4.5.

Another way from PowerShell is to use the Shell.Application com object. But this approach is problematic is well. There's challenges properly detecting when the copy into the zip file finally completes... I've written code to do it before, and then saw it break on the same machine. There seemed to be subtle differences in the zip item properties after a windows update.

As far as a task goes, a node-based task probably makes more sense. I think there's some modules on npm which can handle it.
