### ISSUE TITLE
SqlAzureDacpacDeployment task now fails with invalid Publish Profile

### ISSUE THREAD

**Issue by acgritt** [Microsoft/vso-agent-tasks#1327]
The Azure SQL Server Deployment task was working on February 26th but is now failing as of February 29th with the following error: 

> Invalid Publish Profile 'C:\a\1\s' provided

I do not have a Publish Profile set in the configuration but the debug log is showing that it is being passed a value of 'C:\a\1\s' in the hosted build environment.

**Comment by kmkumaran** [comment]
Thanks for reporting the issue. Are you using hosted agent or private agent? If you are using a private agent, I can provide you a workaround.

**Comment by acgritt** [comment]
I am using one of the Hosted agents.

**Comment by rchien** [comment]
I also hit the same issue with Azure SQL Deploy. Currently I'm trying workaround where I use the PowerShell step, [run this .ps1](https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/SqlAzureDacpacDeployment/DeploySqlAzure.ps1), and pass in the required parameters.

Unfortunately, I'm getting an error `##[error]The specified module './Utility.ps1' was not loaded because no valid module file was found in any module directory.`. But in theory what I'm trying to do should work.

What do I need to do to import Utility.ps1 module? More generally, is there a recommended workaround at this time?

**Comment by kmkumaran** [comment]
@acgritt the issue is happening because the control type of publish profile changed to file picker which is appending default path. @mvvsubbu will plan for hotfix and will update you.

@rchien DeploySqlAzure.ps1 (the script you were referring) and Utility.ps1 bundled in same task and are downloaded when the task runs. All task contents are [here](https://github.com/Microsoft/vso-agent-tasks/tree/master/Tasks/SqlAzureDacpacDeployment). In your case, do you have all required scripts copied explicitly to your script's working directory?

**Comment by mvvsubbu** [comment]
Fixed the issue

**Comment by penguin328-us** [comment]
do you know when it will get deployed

**Comment by kmkumaran** [comment]
@penguin328-us the fix is deployed.
