### ISSUE TITLE
Windows Machine File Copy not Cleaning Target

### ISSUE THREAD

**Issue by Chevyrider28** [Microsoft/vso-agent-tasks#1329]
I’m using the Windows Machine File Copy task with the ‘Clean Target’ option checked, but it’s not removing files from the destination before copying files.  If I rerun the definition you'll see that the files were skipped over after the release was run a second time.

**Comment by pryenugu** [comment]
Hi @Chevyrider28 , for a cleanup we use /MIR option instead of an explicit cleanup (for optimization purposes) but yes the clean target label is a little misleading, we will rename that to MIR or something similar in the task. As for the explicit clean(without /MIR) we have taken the feedback and will see how to improve.
