### ISSUE TITLE
SQL Server Database Deployment task fails when publish profile is not set

### ISSUE THREAD

**Issue by mvvsubbu** [Microsoft/vso-agent-tasks#1336]

**Comment by mvvsubbu** [comment]
Fix checked in. will be rolled out to visualstudio.com in next 24 hrs. I will update the issue once it is rolled out or any change in plan.

**Comment by MilenPavlov** [comment]
Hi, Just wanted to check if this is now resolved? And also if we've installed older version of this task, do we have to remove it and then reinstall it again?

**Comment by RoopeshNair** [comment]
Fix should've been deployed by now. Agent should automatically download the new version of the task, no manual intervention needed.

Do let us know if your run into this issue again.


Roopesh Nair


________________________________

**Comment by MilenPavlov** [comment]
Hi, just tried it again the error message we get is:   ##[error]The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid Publish Profile 'driveName:tfsAgentName\_work\folderName' provided 
However publish profile is not set for this step (at all). We use connection string  and have it as a variable for the environment. The error happens in DeployToSqlServer.ps1 line 49 where the $publishProfile is used as a parameter. Strangely enough this (publishProfile) is set to 'driveName:tfsAgentName\_work\folderName' even if it's not set in the UI for that build step...

**Comment by MilenPavlov** [comment]
Actually our onprem tfs (2015 Update 2 RC2) is using agent version 1.95 and when we try to download the task it errors due to our onprem agent version (1.95) being older that what is required (1.96). Is there a way to upgrade our onprem agent version?

**Comment by mvvsubbu** [comment]
This change happened in m96 milestone, where as TFS 2015 U2 is coming out from m95 milestone. So in your case pick the task from m95 branch use it there this problem is not present and it should work.
