### ISSUE TITLE
NuGetPublisher enhancement

### ISSUE THREAD

**Issue by Allann** [Microsoft/vso-agent-tasks#1400]
Nuget 3.3 introduced an improved folder structure that can be published to using a similar command as push except they called it Add.  Is there a chance this can be included, specifically for On Prem builds.

**Comment by vtbassmatt** [comment]
With TFS vNext we're introducing package management (already shipped in VSTS). That removes the need to deal with fileshares for NuGet. I'm not very inclined to take work that moves the task back towards fileshares.

**Comment by Allann** [comment]
Understandable, but our company use the tasks to build (internal build agent/servers) and our applications are not and probably will not use dnx in the near future, we also have an internal company NuGet server and would prefer not to install a full NuGet server.

**Comment by vtbassmatt** [comment]
Understood. See [here](https://github.com/Microsoft/tfs-cli/blob/master/docs/buildtasks.md) for information on creating and uploading your own build tasks (potentially forking ours - you can give it a new GUID and it won't be overwritten by future updates).

Package management in TFS won't require you to run your own NuGet server at all. It's built into the product.

**Comment by Allann** [comment]
As far as I understand, the link you posted and all the instructions for deploying custom tasks are all related to VSO because you can't login to On-Prem TFS with a personal access token.  Therefore, I am unable to upload custom tasks to our On-Prem server.  Or am I missing something?
I'm sorry but I don't understand your final sentence.  Any chance you can shed some light on that?  
Thank you for your time so far.

**Comment by vtbassmatt** [comment]
Ah, sorry. I'm very cloud-focused and forgot that on-prem doesn't have PATs until Update 2. @chrisrpatterson how do on-prem customers upload new build tasks?

My final comment was addressing your statement "we prefer not to install a full NuGet server". I work on [Package Management](https://marketplace.visualstudio.com/items?itemName=ms.feed) which provides a NuGet (and soon, npm) service directly in TFS. There won't be a separate server to set up and manage, it will be a feature of the product.

Feel free to ping me at mattc@xbox.com (yes, funny domain because I used to work in Xbox before coming to TFS) if you want to discuss further!
