### ISSUE TITLE
SqlAzureDacpacDeployment password with $ character

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/vso-agent-tasks#1417]
A $ character in your target database password (even inside a variable) followed by one or more numbers/letters gets replaced with an empty string, and then SqlPackage fails to connect to the database because it is not using the password you specified.  I am guessing it is getting treated as a variable in powershell when it shouldn't be?

**Comment by Ajay-MS** [comment]
@gregjhogan  Thanks for your feedback and have fixed this issue. This will be available in next release.

**Comment by santoshpatha12** [comment]
What is fix you have applied to accept $ character in powershel script?

**Comment by Ajay-MS** [comment]
@santoshpatha12 

1st way of resolving is using escape characters.
Refer PR - [Resolving dollar character ](https://github.com/Microsoft/vsts-rm-extensions/pull/19)

In Sql Azure Task we were facing problem because we were doing **Invoke-Expression** which expands string so we changed Invoke-Expression call to a method call.
