### ISSUE TITLE
Javascript implementation of the Maven task fails on hosted agents

### ISSUE THREAD

**Issue by HSAR** [Microsoft/vso-agent-tasks#1423]
Reproduction steps:

1. Check out from master
2. Edit the Maven task.json and task.loc.json to remove the Powershell script data
3. Upload using TFX-CLI
4. Run task on a hosted machine

Fails with:
[2_Maven pom.xml.txt](https://github.com/Microsoft/vso-agent-tasks/files/184291/2_Maven.pom.xml.txt)

**Comment by madhurig** [comment]
Hi,

Can you elaborate on why you are trying to run the node version of this task on Windows? Currently the node version of maven task is not supported on Windows, we recommend you use the powershell version on Windows. The hosted pool machines run Windows. 

The reason the task is failing is as noted in the log, mvn is not found in the %PATH%. Since the pool is not managed by you, we have no idea where mvn is installed. If you are using your own Windows build machine, you can add mvn to the %PATH% or specify the "Maven Path" under "Advanced".

Regards,
Madhuri

**Comment by HSAR** [comment]
Thanks for responding, Madhuri. I have traced this issue, as you say, down to a missing variable on the hosted machine configuration and this should be resolved as soon as that can be changed.
