### ISSUE TITLE
DeployVisualStudioTestAgent 1.0.25 fails

### ISSUE THREAD

**Issue by Louliloul** [Microsoft/vso-agent-tasks#1431]
The newly deployed version 1.0.25 is failing at the very beginning of the task execution, whereas 1.0.24 was successful with the same task configuration

Message:
1. Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\DeployVisualStudioTestAgent\1.0.25\DeployTestAgent.ps1
2.##[debug]resourceFilteringMethod = machineNames
3. ##[error]A parameter cannot be found that matches parameter name 'Persist'.
4. ##[error]Cannot bind argument to parameter 'MachineEnvironment' because it is null.

Task configuration:
1 machine fqdn, with admin login and password, HTTP, select by machine names
Agent config: login, password, interactive
Advanced: default

**Comment by ncipollina** [comment]
I've discovered the same thing.  Mine in particular is occurring in the DeployAzureResourceGroup task on this line:
$environment = Register-Environment -EnvironmentName $outputVariable -EnvironmentSpecification $machineSpecification -WinRmProtocol "HTTPS" -Connection $connection -TaskContext $distributedTaskContext -TagsList $tagsList -Persist

Looks like -Persist is no longer a valid parameter for Register-Evnrionment.  My releases are currently all failing.

**Comment by nathankitchen** [comment]
Also finding this same issue. I'm spinning a new ARM-based VM from JSON as part of a nightly build, so the target machine is "clean". It's a Win 2012 R2 box, PS 4.0. Logs below:

`Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\DeployVisualStudioTestAgent\1.0.25\DeployTestAgent.ps1`
`##[debug]resourceFilteringMethod = machineNames`
`##[error]A parameter cannot be found that matches parameter name 'Persist'.`
`##[error]Cannot bind argument to parameter 'MachineEnvironment' because it is null.`

**Comment by nigurr** [comment]
@kmkumaran can you please look into this?
I guess this is because the Build Agent didn't get new libraries but the tasks got upgraded.

**Comment by pryenugu** [comment]
@Louliloul , @ncipollina , @nathankitchen : Are you seeing this issue in hosted agents? Or are you seeing this in on-premise agents?

**Comment by Louliloul** [comment]
For my part, it's the default hosted agent.

**Comment by pryenugu** [comment]
@Louliloul , @ncipollina , @nathankitchen, we are working to get this resolved as quickly as possible for the hosted agents. This issue only occurs in the hosted agent. As a workaround, you can go ahead and requeue/reconfigure your definitions to work with on-premise downlaoded agents.

**Comment by ncipollina** [comment]
I am also using the hosted agent.  I have spent my entire morning trying to get this working on a build agent running on an azure VM and I'm running into the issue document here https://github.com/Microsoft/vso-agent-tasks/issues/1374

Any idea of when this issue will be resolved?  I am currently unable to release anything due to these issues.

**Comment by AshwiniChalla** [comment]
Can you rerun now. We have made the fix.

**Comment by ncipollina** [comment]
Looks like things are working again.

**Comment by AshwiniChalla** [comment]
Thanks for confirming.

**Comment by Louliloul** [comment]
Confirmed
