### ISSUE TITLE
Variables passed to build task are not escaped correctly

### ISSUE THREAD

**Issue by compulim** [Microsoft/vso-agent-tasks#1536]
In build/release definitions, assume we have a variable named `abc` and the value is `123&456&789`.

We have a PowerShell build task like this, `Dump-Variable -Value $(abc)`.

The build agent will pass the variable as is. Thus, calling PowerShell like `Dump-Variable -Value 123&456&789`. Then PowerShell will fail and say `&` is invalid.

The build agent should escape & by replacing all instances with `& (prefix with backquote).

This is also true for value with `<` and `>`.

**Comment by ericsciple** [comment]
That's intentional. Otherwise it interferes with the full ability to of passing parameters to a powershell script (e.g. passing arrays or hashtables).

What you could do is specify $env:abc instead. Let PowerShell expand the environment variable. The "$()" syntax for task inputs is just macro replacement.

Another option would be to quote your variable using single quotes (which would reduce the concern to escaping single quotes).

**Comment by compulim** [comment]
Environment is a good idea. Thanks for clarification.
