### ISSUE TITLE
Writing to stderr == error should be optional

### ISSUE THREAD

**Issue by paulsapps** [Microsoft/vso-agent-tasks#279]
So far I have found many tools seems to write to stderr even when there is no error. For example cloning git submodules writes each "cloning into" into std err.

For this reason I think there should be optional to treat writing to stderr as an error and also add a treat none zero return code as an error option. In my case I would like to say that there is only a failure if return code != 0 even if something was written to stderr.

**Comment by bryanmacfarlane** [comment]
In RTM and with the VSO sprint 84 rollout, we defaulted batch script, ps1, cmdline and shellscript tasks to do just that - not treat stderr as a failure.  But for those, we also added an option on the tasks whether you want to fail on stderr.  Outside the script type tasks, specific strongly typed tasks (like npm etc...) do the right thing for those tools.

So, this should be fixed in the next couple weeks rollout.

**Comment by paulsapps** [comment]
Excellent, thanks
