### ISSUE TITLE
XamariniOS does not escape spaces in solution file for nuget restore command

### ISSUE THREAD

**Issue by blsmithers** [Microsoft/vso-agent-tasks#419]
Running XamariniOS v1.0.4.  If the solution file has spaces in it the nuget restore command fails and the build hangs:

[command]/usr/bin/nuget restore /Users/brian/myagent/_work/build/028c6348fb6992c170d51fdb97f4aa007efd9217b6ed97908eb1e308c816cb80/repo/My Solution With Spaces.sln
2015-08-18T13:38:27.708Z: restore: invalid arguments.
2015-08-18T13:38:27.717Z: usage: NuGet restore [<solution> | <packages.config file>] [options]
2015-08-18T13:38:27.718Z: 
2015-08-18T13:38:27.718Z: Restores NuGet packages.

**Comment by madhurig** [comment]
I have a fix for correctly escaping the path but it looks like nuget does not handle spaces in the solution path even when escaped. 

Please check if running this from a terminal window works for you: /usr/bin/nuget restore '/Users/brian/myagent/_work/build/028c6348fb6992c170d51fdb97f4aa007efd9217b6ed97908eb1e308c816cb80/repo/My Solution With Spaces.sln'. Please let us know if you see this work on terminal on your mac. If it fails on the terminal, you will have to update your solution name to not have spaces as a workaround till this is fixed in nuget. 

I am also investigating why the build hangs when nuget restore fails.

**Comment by blsmithers** [comment]
I tried both single quotes and double quotes around the solution path, both work when running on the terminal:

nuget restore '/Users/brian/myagent/_work/build/028c6348fb6992c170d51fdb97f4aa007efd9217b6ed97908eb1e308c816cb80/repo/My Solution With Spaces.sln'
nuget restore "/Users/brian/myagent/_work/build/028c6348fb6992c170d51fdb97f4aa007efd9217b6ed97908eb1e308c816cb80/repo/My Solution With Spaces.sln"

**Comment by madhurig** [comment]
That's great, I will get the fix committed soon. Can you provide what version of Xamarin Studio/nuget you have installed on your Mac?

**Comment by blsmithers** [comment]
Great, thanks!

I'm running:
nuget v 2.8.5.0
Xamarin Studio v 5.9.5 (build 9)
Xamarin.iOS v 8.10.4.46

**Comment by madhurig** [comment]
Thank you, I had to upgrade my Xamarin Studio + nuget and was able to test out my fix, PR created: https://github.com/Microsoft/vso-task-lib/pull/1

**Comment by bryanmacfarlane** [comment]
merged

**Comment by blsmithers** [comment]
I feel like this is something I'm doing wrong but I can't quite figure this out, apologies in advance.  I have updated to the vsoagent-installer:

sudo npm install vsoagent-installer -g

and the output indicates vso-task-lib@0.4.5

I then execute vsoagent-installer on my agent which pulls in the new scripts. For vso-task-lib the package.json indicates a version of 0.4.5 but the change above does not exist in lib/vsotask.js. This is consistent with what I'm seeing in /usr/local/lib/node_modules/vsoagent-installer/node_modules/vso-task-lib.

It's weird I'm seeing the 0.4.5 version but not an updated vsotask file, am I missing a step?  Thanks in avance
