### ISSUE TITLE
Searching for how to use "demands" in custom task.json

### ISSUE THREAD

**Issue by staticcat** [Microsoft/vso-agent-tasks#528]
Looking for help on how the demands entry works for tasks works. My current understanding is that it will search the agent for the command using a command like where. Is this correct? If not is there some help I can view on using this feature for our own task?

I am looking to have a demand on our script tool executable. Having this picked up automatically by the agent is preferred. Working like the chef action would be great. Currently it isn't clear how the chef action is demanding that chef be installed on the agent and the agent is picking that up automatically. 

Thanks.

**Comment by bryanmacfarlane** [comment]
Right now, tasks cannot contribute to the capability scan.  We have a story on the backlog to address this.  Currently the agent scans for a bunch of well known tools and capabilities.  

workarounds:
(1) not demand anything, check in your task and error grecefully
(2) demand in your task and  

It's on our backlog to fix.  The reason we haven't is if the task carries the capability scan, we need another mechanism to store that script and download because tasks are pulled JIT at build time so it's tool late.  The other option is to allow a series of commands to run in the json (but is it where toolname or which toolname?).  When .net agents can run js tasks (via node ... soon), it can be one script tech.

Hope all that makes sense.  Closing since on our backlog.
