### ISSUE TITLE
Manually uploading build tasks from this repo

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#545]
Is it safe to use some of these build tasks by manually uploading them, before they are officially released? What happens if they are officially rolled out and already are manually uploaded to a tenant? Or should we make sure to have them deleted before official deployment?

**Comment by pascalberger** [comment]
@chrisrpatterson Do you know how this is handled? (I think we will have this constellation with the NuGet Task and the m88 release).

**Comment by bryanmacfarlane** [comment]
You can do this but getting closer is safer.  For example, pushing to VSO means you're pretty close.  Pushing latest to RTM server might not be as safe since that's now many months ago.

Technically, there's a minagentVersion property in the task.json.  Sprint 83 is RTM and the currently released sprint is 87/88 (88 rolling now).  The server will reject if not appropriate.  Don't touch that, there's a reason it's incremented if it is.  We try our best not to. 

How its handled is the server takes the latest version of the task.  It unions the in-the-box deployment level tasks with your custom tasks and takes latest.  I believe your custom one will win if equal.

You're best to take from Release/* branch since master is code that's being actively worked on

**Comment by pascalberger** [comment]
Thanks. We're on VSO, so agent version is not that big of a deal. I was more concerned about custom tasks overriding in-the-box tasks, but as you mention this should be no issue.

Does this mean that if I upload a task from this repo to VSO which is later rolled out in an official update I can safely delete the custom task (through `tfx build tasks delete`) without having the in-the-box task affected?

**Comment by bryanmacfarlane** [comment]
That should be the case.  If you don't see that, it's a bug. :)
