### ISSUE TITLE
VSO Agent does not update system requirements

### ISSUE THREAD

**Issue by ghostinside** [Microsoft/vso-agent-tasks#569]
During the gulp build configuration got an issue that if the required modules like node or npm were not installed and were not shown in the agent`s system requirements, even after install you will not find them there and run the build, just to install new agent

Thx Alex

**Comment by chrisrpatterson** [comment]
Those tools must be in the path of the agent process in order to be located properly. In many cases people make the mistake of installing the tools as themselves which puts them in the users path.  Then they configure the agent as network service and those tools are not in the path.

If you change the environment for the agent service account you will need to restart the agent process to update the capabilities.
