### ISSUE TITLE
Build fails with "##[error]Illegal characters in path." - logs not reporting task or path that's causing the issue

### ISSUE THREAD

**Issue by PreetSangha** [Microsoft/vso-agent-tasks#673]
I've just run into this issue and after hunting around I've discovered what it was and, though it was an error on my part, I think the error reporting could be improved to catch this error and report to aid other people's diagnostics. Perhaps it could show the task name and the property that's wrong?

Web log
![2015-10-23_16-10-55](https://cloud.githubusercontent.com/assets/15098094/10683766/f79d7e6c-79a1-11e5-8417-49d3e77ce266.png)

Build.log
![2015-10-23_16-12-56](https://cloud.githubusercontent.com/assets/15098094/10683769/fe0bd76c-79a1-11e5-99e2-59a9d7d9175a.png)

I found this in the agent's diagnostics. And this was what lead me to the actual error
![2015-10-23_16-16-17](https://cloud.githubusercontent.com/assets/15098094/10683770/fffd44fc-79a1-11e5-874b-c9588e2fad95.png)

the actual error (simple example) for reference 
![2015-10-23_16-23-30](https://cloud.githubusercontent.com/assets/15098094/10683816/7f8e8d52-79a2-11e5-8d19-62699fbf3a2b.png)

**Comment by PreetSangha** [comment]
Also here is another one I get from time to time. I don't know why I get this but usually if I submit the build it clears up

![2015-10-23_17-09-35](https://cloud.githubusercontent.com/assets/15098094/10684417/53f6885a-79a9-11e5-9563-4303cbc3d366.png)

**Comment by ericsciple** [comment]
Using the example you provided, I can't repro the issue you are describing. Based on your repro steps i'm getting an error that bubbles from the PowerShell task, not the Get Sources task. And the error message I'm getting is different - and appears to be a helpful error. Closing the issue for now. Let me know if there's something i'm missing and we can reopen the issue. Here's the steps i used:
1) Added a PowerShell task
2) Set the script filename input to: { & "_Tools/Test.proj" }
3) Ran the build.

The separate access denied issue is due to some process holding a lock one of your files. You can run process monitor to identify the offending process. My guess is that it's a tool that was invoked from a previous build. Incremental build may alleviate the issue (if that's an option for your case). Ultimately i think it would be helpful to add code that basically does what process monitor does: track down what process is holding the file and tell you in the error message. It's an item that's currently on the backlog. Feel free to open a separate issue if you want to track it's completion.

**Comment by PreetSangha** [comment]
Hi there. 

Sorry for the delay in responding we had a public holiday. 

Looking at the log above istm that the Get Sources finishes. I have just recreated this 

![2015-10-27_10-49-52](https://cloud.githubusercontent.com/assets/15098094/10743615/0c6283de-7c99-11e5-959c-315c6f6ab3f5.png)


I'm using an on premise TFS server and our agent is: 1.83.2, so perhaps you've already fixed this issue. 

Thanks for the advice on the locking process.

**Comment by ericsciple** [comment]
@PreetSangha sorry i just saw you replied (issue was closed). The illegal characters in path during get sources is actually masking "file in use" error during clean step. I think the fix made the cutoff for for update 1, if not then it will be in update 2.

**Comment by KirkhapAuto** [comment]
Thank you.
