### ISSUE TITLE
Link to Sonar wrong with sonar.branch

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#711]
In a build definition I pass the branch to Sonar in the begin analysis step like this:

    /d:sonar.branch=MyBranch

The link in the summary.md file showed on build summary page doesn't reflect this and still links to the Sonar Dashboard with `http://sonar:9000/dashboard/index/MyProject` instead of linking to the project corresponding to the branch. 

This is not an issue with the VSO Sonar task itself, but with the wrapped Sonar MSBuild runner which [only passes the Dashboard Url](https://github.com/SonarSource/sonar-msbuild-runner/blob/8247b08707b8bafca857b2948c96f127454f130b/SonarQube.TeamBuild.PostProcessor/SummaryReportBuilder.cs#L94), instead of considering the branch too, or with Sonar itself which maybe doesn't return the Url to the MSBuild runner. Please let me know if there's a more appropriate way to fill an issue on this.

**Comment by bgavrilMS** [comment]
Hi Pascal. Thank you for taking the time to report this. 

You're right, the root cause for this is the Sonar Msbuild Runner, which is developed in collaboration with SonarSource. We log issues for this component in Jira. I logged the bug you described at: 

https://jira.sonarsource.com/browse/SONARMSBRU-157

Please note that we've just release a new version of the Sonar Msbuild Runner bits, and we're in the process of planning the next release.

**Comment by pascalberger** [comment]
@bgavrilMS Thanks! Where is the proper place to report issues with the Sonar MSBuild Runner? Permissions at https://jira.sonarsource.com/projects/SONARMSBRU seem to be restricted to not allow anyone to add issues.
