### ISSUE TITLE
PowerShell task uses ps profile that lacks some modules (like PowerShellGet)

### ISSUE THREAD

**Issue by anpur** [Microsoft/vso-agent-tasks#818]
# How to reproduce:
1. Create `test.ps1` with `Get-Module -ListAvailable` content (via sources or via command line task `powershell -c Set-Content test.ps1 'Get-Module -ListAvailable'`)
1. Run it from command line task `powershell -c test.ps1`
1. Run it from PowerShell task `test.ps1`
1. Observe different folders and different sets of modules available

## Difference in my case
Module folders available from command line's powershell:
- C:\Users\sbuilder\Documents\WindowsPowerShell\Modules
- C:\Program Files\WindowsPowerShell\Modules
- C:\Windows\system32\WindowsPowerShell\v1.0\Modules

Module folders available from PowerShell task:
- C:\Windows\system32\WindowsPowerShell\v1.0\Modules
- C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement
- D:\builds\agent\worker\Modules

Most probably it was caused by special config used by PowerShell task.

## Effects
This issue makes usage inconsistent and forces to avoid PowerShell task at all costs, as it is not possible to install modules there, use already installed modules, etc.

**Comment by chrisrpatterson** [comment]
It actually runs with -NoProfile and uses the PSModulePath environment variable so any modules defined in paths referenced in the users or systems PSModulePath environment variable should be useable.

**Comment by anpur** [comment]
Buy why it uses `-NoProfile`? User anyway will use command line task to run single powershell commands with `powershell.exe` which utilizes current user profile.

Also, it makes setup less flexible: instead of configuring builder powershell profile administrator will have to add all folders to `PSModulePath`.

Anyway, thanks a lot for reply, now I know how to work around this issue.

**Comment by ericsciple** [comment]
Not setting -noprofile is something I'd like to expose it as an advanced option. I need to prioritize it and talk it over with @chrisrpatterson

**Comment by ericsciple** [comment]
Something else is going on here not caused by the presence of the -noprofile switch. I've got a repro and trying to figure out what is going on.

**Comment by ericsciple** [comment]
Regardless of any switches (noprofile or otherwise) passed to powershell.exe, it appears that powershell.exe itself overrides the PSModulePath if it hasn't been overridden at the process level.

Because the agent adds it's own PS module directory to the process-level PSModulePath env var, it's interfering with the override behavior of PowerShell.exe.

I don't think any of the agent's modules can be loaded by ad-hoc scripts anyway. Perhaps the best thing here is for the agent to stay out of the way and not touch the PSModulePath before invoking ad-hoc powershell scripts.

I need to talk this over with my program manager and think on this a bit.

**Comment by ericsciple** [comment]
the psmodulepath issue was fixed recently.
