### ISSUE TITLE
WindowsMachineFileCopy Error EnvironmentName

### ISSUE THREAD

**Issue by msisterna** [Microsoft/vso-agent-tasks#867]
Hi,
I'm using the VSO and I can't copy any file into my server. Last week this task worked fine but this week it doesn't work. I've discovered that the script version changed from 1.0.10 to 1.0.14.
The error is:

2015-11-23T20:23:28.0631919Z ##[debug]Starting Register-Environment cmdlet call for environment : MyMachineGroupName with filter  
2015-11-23T20:23:28.3351748Z ##[error]System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'EnvironmentName'.

Any idea?, thanks a lot.

**Comment by blsher** [comment]
I've found that the new admin/password feature is ignoring machine groups.  The only way i've found a way around is, creating 1 machine group with 1 machine, and using the new machine groups name.... which defeats the purpose of labels..etc.  No idea what's going on, or some change but it seems the concept of a "machine group filter" has been busted.

**Comment by kmkumaran** [comment]
The error message on Register-Environment is because of hosted agent still in older bits. Hosted Agents are due for an upgrade and should get fixed soon. As a workaround you can download the latest agent bits and setup an on-prem agent. 

WindowsMachineFileCopy task can take the machine names inline and also can take machine group. If you specify machine names or IP inline, then you need to provide credentials. With this option, you can target only those set of machines you intend to.

**Comment by msisterna** [comment]
Hi, as you said, the workaround was setup an on premise agent and work fine. 
Thanks for help me.

**Comment by EmanuelDejonghe** [comment]
When can we expect the upgrade for the Hosted Agents? Switching to an on premise agent is not really an option for me...

**Comment by kmkumaran** [comment]
CJ is upgrading the agents. Have assigned the issue so that he can update you on timeline and progress.

**Comment by beverts312** [comment]
Any updates on this @thechrisjohnson ?

**Comment by thechrisjohnson** [comment]
The hosted pools have been updated with the latest agent. Everything should work now.
