### ISSUE TITLE
SonarQubePreBuild: MSBuild.SonarQube.Runner cannot run analysis against TLS versions higher than 1.0

### ISSUE THREAD

**Issue by AndreasBieber** [Microsoft/vso-agent-tasks#900]
The provided MSBuild.SonarQube.Runner in the SonarQubePreBuild task cannot run analysis against HTTPS hosted SQ servers using TLS versions higher than 1.0.

Best regards
 Andreas

**Comment by bgavrilMS** [comment]
Hi @AndreasBieber , 

The fix will be released with version 1.1 of the Msbuild SonarQube Runner, which will be available with version 4.4 of the C# plugin. The release is planned in the next few weeks. 

I'm going to close this issue because the tasks do not need to be updated - all you need is the new C# plugin.
