### ISSUE TITLE
AzureResourceGroupDeployment is looking for env:build_sourcesdirectory which isn't being set

### ISSUE THREAD

**Issue by simonsabin** [Microsoft/vso-agent-tasks#975]
The AzureResourceGroupDeployment task is referencing the environment variable build_sourcesDirectory which is being set for builds but not for releases.

Some other way needs to check if a blank value has been specified for the template file and parameters file

**Comment by RoopeshNair** [comment]
Hosted agents are due for an upgrade. It should get fixed in the upcoming deployments. 

For this specific issue, have you defined "Output variable" field for the AzureResourceGroup task? Do you intend to use this variable in subsequent tasks for example "PowerShell on Target" task? If not, you can clear this field and re-run the release - the issue should go away.

If you do intend to use the output variable in subsequent tasks, then for now you need to setup private agent. 

Roopesh Nair

**Comment by pavanadepu2** [comment]
Thanks much for the feedback Simon.
This is a known issue and getting addressed in the next deployment.

**Comment by KrishnaAdityaB** [comment]
Fixed with PR #991 
Should be deployed in next 5-6 weeks.
