### ISSUE TITLE
Scaling out VSO Build Agents

### ISSUE THREAD

**Issue by johnkattenhorn** [Microsoft/vso-agent-tasks#999]
We've been getting great performance by hosting our own VSO Build Agent in a DS2 Virtual Machine but we want to increase the density as the server has plenty of head room.

I've read the documentation here:

https://msdn.microsoft.com/en-us/library/dd793166.aspx

But I just want to confirm the steps, so if I want to run multiple vNext Build Agents I need to install the TFS 2015 Build Service onto the server first ?

Will this then allow me to register multiple vNext Build Agents ? Is this correct ? We literally run the installer from difference directories is what I read from the documentation.

Just to be clear we do not use the XAML build at all anymore, it's all vNext.

Thanks in advance

**Comment by ericsciple** [comment]
Here's the admin overview page you want: https://msdn.microsoft.com/en-us/Library/vs/alm/Build/agents/admin

For Windows agents, here's the config steps: https://msdn.microsoft.com/en-us/Library/vs/alm/Build/agents/windows

Just download the agent on the box and run through the config steps.

**Comment by ericsciple** [comment]
Closing this issue. Feel free to reopen.

**Comment by bgoldman69** [comment]
So im going to call out @ericsciple  here for not saying "yes" or "no" to the original question and confirming or denying the required / requested outcome.  I believe the answer is "yes - and you do just point to a different directory, but you need to make sure to download the agent each time you do an install because there is some configuration done pre-download each time" but it would be a good idea to see that in the thread.

**Comment by ericsciple** [comment]
@bgoldman69 yes you can run multiple agents on one machine, just make sure they dont point to the same _work folder

**Comment by ericsciple** [comment]
yes the docs do not seem to address specifically running multiple agents on one machine. i'll follow-up with appropriate folks offline
